name: "CI"

on:
  push:
    branches:
      - "main"
      - "master"
      - "dev_sooyean"
  pull_request:
    branches:
      - "main"
      - "master"
      - "dev_sooyean"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Spec:
    uses: "sooyean-hoo/cat-github-actions/.github/workflows/module_ci.yml@dev_sooyean"
    secrets: "inherit"

# Not working as VMs all down.
#   Acceptance:
#     needs: Spec
#     uses: "sooyean-hoo/cat-github-actions/.github/workflows/module_acceptance.yml@dev_sooyean"
#     secrets: "inherit"
#     with:
#       flags: " --exclude-platforms '[\"CentOS-7\",\"CentOS-8\",\"OracleLinux-8\",\"RedHat-7\",\"RedHat-8\",\"Ubuntu-18.04\",\"OracleLinux-7\",\"Scientific-7\",\"SLES-12\"]'" # Only way for Acceptance CI to run in the absence of vmpooler's VMs
